rmt_remote/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('trash.urls')),
]

trash/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.trashcan_view, {'name': None}, name='index'),
    url(r'^newcan$', views.CreateTrashcanView.as_view(), name='newcan'),
    url(r'^trashcan/$', views.trashcan_view, {'name': None}, name='trashcan'),
    url(r'^trashcan/(?P<name>\w+)/$', views.trashcan_view, name='trashcan'),
    url(r'^task/$', views.task_view, {'task_id': None}, name='task'),
    url(r'^task/(?P<task_id>\d+)$', views.task_view, name='task'),

    url(r'^put$', views.put, name='put'),
    url(r'^ajax/erase$', views.ajax_erase),
    url(r'^ajax/restore$', views.ajax_restore),
]

trash/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import rmt_async.trashcan

from django.db import models
from threading import Lock


class Trashcan(models.Model):
    _instances = {}
    _instances_lock = Lock()

    name = models.CharField(max_length=100, unique=True, null=False)
    path = models.CharField(max_length=1000)
    next_action_id = models.IntegerField(default=1)

    @property
    def items(self):
        return list(self.instance.items())

    @property
    def instance(self):
        with self._instances_lock:
            if self.id not in self._instances:
                instance = rmt_async.trashcan.AsyncTrashcan(
                    self.path,
                    initial_action_id=self.next_action_id
                )
                self._instances[self.id] = instance
            return self._instances[self.id]

    def __str__(self):
        return self.name

    def create_task(self, task_type, targets):
        task = Task.objects.create(
            trashcan=self,
            task_type=task_type,
            status=Task.STATUS_DRAFT,
        )
        for record_id in targets:
            TaskTarget.objects.create(
                task=task,
                trashcan=self,
                target=record_id,
                status=TaskTarget.STATUS_DRAFT
            )
        task.run()
        return task


class TaskTargetError(models.Model):
    reason = models.CharField(max_length=300)

    def __str__(self):
        return self.reason


class TaskTarget(models.Model):
    STATUS_SUCCESS = 0
    STATUS_FAIL = 1
    STATUS_DRAFT = 2
    STATUS = (
        (STATUS_SUCCESS, 'Success'),
        (STATUS_FAIL, 'Fail'),
        (STATUS_DRAFT, 'Draft'),
    )

    task = models.ForeignKey('Task')
    trashcan = models.ForeignKey('Trashcan')
    target = models.CharField(max_length=100)
    status = models.IntegerField(choices=STATUS)
    action_id = models.IntegerField(null=True)
    error = models.ForeignKey('TaskTargetError', null=True)


class Task(models.Model):
    STATUS_SUCCESS = 0
    STATUS_FAIL = 1
    STATUS_DRAFT = 2
    STATUS_EXECUTING = 3
    STATUS = (
        (STATUS_SUCCESS, 'Success'),
        (STATUS_FAIL, 'Fail'),
        (STATUS_DRAFT, 'Draft'),
        (STATUS_EXECUTING, 'Executing'),
    )

    TASK_TYPE_PUT = 0
    TASK_TYPE_ERASE = 1
    TASK_TYPE_RESTORE = 2

    TASK_TYPE = {
        TASK_TYPE_PUT: 'Put',
        TASK_TYPE_ERASE: 'Erase',
        TASK_TYPE_RESTORE: 'Restore',
    }

    TASK_METHODS = {
        TASK_TYPE_PUT: rmt_async.AsyncTrashcan.put,
        TASK_TYPE_ERASE: rmt_async.AsyncTrashcan.erase,
        TASK_TYPE_RESTORE: rmt_async.AsyncTrashcan.restore,
    }

    task_id = models.AutoField(primary_key=True)
    task_type = models.IntegerField()
    trashcan = models.ForeignKey('Trashcan', on_delete=models.CASCADE)
    status = models.IntegerField()

    def __str__(self):
        return '{} :: {}'.format(self.TASK_TYPE[self.task_type], self.trashcan.name)

    def run(self):
        for task_target in TaskTarget.objects.filter(task=self):
            try:
                target = (
                    task_target.target
                    if self.task_type == Task.TASK_TYPE_PUT
                    else int(task_target.target)
                )
                action_id = self.TASK_METHODS[self.task_type](
                    self.trashcan.instance,
                    target
                )
                task_target.action_id = action_id
                self.trashcan.next_action_id += 1
            except Exception as e:
                task_target.status = TaskTarget.STATUS_FAIL
                task_target.error = TaskTargetError.objects.create(
                    reason=str(e)
                )
            else:
                task_target.status = TaskTarget.STATUS_DRAFT
                task_target.save()

        self.trashcan.save()
        self.save()

trash/forms.py
from django import forms

from .models import Trashcan


class CreateTrashcanForm(forms.ModelForm):
    class Meta:
        model = Trashcan
        fields = ('name', 'path')


class PutTaskForm(forms.Form):
    targets = forms.CharField(max_length=10000, widget=forms.Textarea)

trash/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import FormView

from .forms import CreateTrashcanForm, PutTaskForm
from .models import Trashcan, TaskTarget, Task


class CreateTrashcanView(FormView):
    form_class = CreateTrashcanForm
    success_url = '/'

    def form_valid(self, form):
        Trashcan.objects.create(
            name=form.data.get('name'),
            path=form.data.get('path'),
        )
        return super(CreateTrashcanView, self).form_valid(form)


def put(request):
    trashcan = Trashcan.objects.get(id=request.POST.get('trashcan_id'))
    targets = [target.strip() for target in request.POST.get('targets').split('\n')]
    task = trashcan.create_task(Task.TASK_TYPE_PUT, targets)
    return redirect('task', task_id=task.task_id)


def index(request):
    return render(request, 'trash/index.html')


def trashcan_view(request, name):
    context = {
        'trashcan_form': CreateTrashcanForm(),
        'put_form': PutTaskForm(),
        'trashcans': Trashcan.objects.all()
    }
    if name is not None:
        trashcan = get_object_or_404(Trashcan, name=name)
        context['current_trashcan'] = trashcan
    return render(request, 'trash/trashcan.html', context)


def task_view(request, task_id):
    context = {
        'trashcan_form': CreateTrashcanForm(),
        'tasks': Task.objects.all()
    }

    if task_id is not None:
        current_task = get_object_or_404(Task, task_id=task_id)
        targets = TaskTarget.objects.filter(task=current_task)
        context['current_task'] = current_task
        context['targets'] = targets

    return render(request, 'trash/task.html', context)


def ajax_erase(request):
    if request.is_ajax() and request.method == 'POST':
        trashcan = Trashcan.objects.get(id=request.POST.get('trashcan_id'))
        targets = request.POST.getlist('targets[]')
        task = trashcan.create_task(Task.TASK_TYPE_ERASE, targets)
        return JsonResponse({
            'status': 'success',
            'redirect': reverse('task', kwargs={'task_id': task.task_id})
        })
    else:
        return JsonResponse({})


def ajax_restore(request):
    if request.is_ajax() and request.method == 'POST':
        trashcan = Trashcan.objects.get(id=request.POST.get('trashcan_id'))
        targets = request.POST.getlist('targets[]')
        task = trashcan.create_task(Task.TASK_TYPE_RESTORE, targets)
        return JsonResponse({
            'status': 'success',
            'redirect': reverse('task', kwargs={'task_id': task.task_id})
        })
    else:
        return JsonResponse({})

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery=1 %}
        <title>rmt_remote</title>
        <meta charset="UTF-8">
        {% block static %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

trash/templates/trash/base.html
{% extends 'base.html' %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'trash/styles.css' %}">
{% endblock %}

{% block content %}
    {% block trash_content %}
    {% endblock %}
{% endblock %}

trash/templates/trash/create_trashcan.html
{% load bootstrap3 %}

<div class="modal fade" role="dialog" id="createTrashcan">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action='{% url 'newcan' %}'>
                    {% csrf_token %}
                    {% bootstrap_form trashcan_form %}
                    {% buttons %}
                    <button type="submit" class="btn btn-default">Create</button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</div>

trash/templates/trash/index.html
{% extends 'trash/base.html' %}

{% block trash_content %}
{% endblock %}

trash/templates/trash/put_task.html
{% load bootstrap3 %}

<div class="modal fade" role="dialog" id="putTask">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" action='{% url 'put' %}'>
                    {% csrf_token %}
                    {% bootstrap_form put_form %}
                    <input type="hidden" name="trashcan_id" value="{{ current_trashcan.id }}"></input>
                    {% buttons %}
                    <button type="submit" class="btn btn-default">Put</button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</div>

trash/templates/trash/task.html
{% extends 'trash/base.html' %}

{% block trash_content %}
<div class="full-screen">
    <div class="header navbar-default panel panel-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">rmt_remote</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'trashcan' %}">Trashcans</a></li>
                <li class="active"><a href="{% url 'task' %}">Tasks</a></li>
                <li><a href="" data-toggle="modal" data-target="#createTrashcan">Create trashcan</a></li>
            </ul>
        </div>
    </div>
    <div class="main">
        <div class="left panel panel-default list-group">
            {% for task in tasks %}
            <a class="list-group-item{% if task == current_task %} active{% endif %}" href="{% url 'task' task.task_id %}">{{ task }}</a>
            {% endfor %}
        </div>
        {% if current_task %}
        <div class="middle">
            <div class="info-panel panel panel-default">
                <table>
                    <tr>
                        <td valign="middle">
                            <h4>{{ current_task }}</h4>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="contents-panel panel panel-default">
                <table class="table">
                    <thead>
                        <th class="col-md-4">Status</th>
                        <th class="col-md-4">Target</th>
                        <th class="col-md-4">Error</th>
                    </thead>
                    <tbody>
                        {% for target in targets %}
                        <tr>
                            <td>{{ target.get_status_display }}</td>
                            <td>{{ target.target }}</td>
                            <td>{{ target.error }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% include 'trash/create_trashcan.html' %}
{% endblock %}

trash/templates/trash/trashcan.html
{% extends 'trash/base.html' %}
{% load staticfiles %}

{% block trash_content %}
<div class="full-screen">
    <div class="header navbar-default panel panel-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">rmt_remote</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'trashcan' %}">Trashcans</a></li>
                <li><a href="{% url 'task' %}">Tasks</a></li>
                <li><a href="" data-toggle="modal" data-target="#createTrashcan">Create trashcan</a></li>
            </ul>
        </div>
    </div>
    <div class="main">
        <div class="left panel panel-default list-group">
            {% for trashcan in trashcans %}
            <a class="list-group-item{% if trashcan == current_trashcan %} active{% endif %}" href="{% url 'trashcan' trashcan.name %}">{{ trashcan }}</a>
            {% endfor %}
        </div>
        {% if current_trashcan %}
        <script>var currentTrashcanId = {{ current_trashcan.id }};</script>
        <div class="middle">
            <div class="info-panel panel panel-default">
                <table>
                    <tr>
                        <td align="left" width="80px"><img src="/static/trash/trashcan.png" height="60px"/></td>
                        <td valign="middle">
                            <h4>{{ current_trashcan }}</h4>
                            {{ current_trashcan.path }}
                        </td>
                        <td align="right">
                            <div class="btn-group" role="group">
                                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#putTask">Put</button>
                                <button type="button" class="btn btn-default" id="eraseButton">
                                    Erase
                                </button>
                                <button type="button" class="btn btn-default" id="restoreButton">
                                    Restore
                                </button>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="contents-panel panel panel-default">
                <table class="table" id="contentsTable">
                    <thead>
                        <th>ID</th>
                        <th>Path</th>
                        <th>Size</th>
                    </thead>
                    <tbody>
                        {% for item in current_trashcan.items %}
                        <tr class="clickable-row">
                            <td class="id-cell">{{ item.record_id }}</td>
                            <td>{{ item.path }}</td>
                            <td>{{ item.size|filesizeformat }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% include 'trash/create_trashcan.html' %}
{% include 'trash/put_task.html' %}
<script src="{% static 'trash/trashcan.js' %}"></script>
{% endblock %}